### PR TITLE
Fixing setup instructions

### PR DESCRIPTION
**Pull request by eolecvk**
Setup cuda 12 setup workflow did not work (setuptools not found in environment)
Streamlining and fixing issues in setup instructions

### CODE REVIEW

**Comment by eolecvk** [comment]
`conda install cudatoolkit=11.6` fails (not found).
May want to upgrading to cudatoolkit=11.8?

**Comment by eolecvk** [comment]
`pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html` freezes

**Comment by eolecvk** [comment]
@chuanli11 the setup instructions did not work on A100 or A10 instances.
Could you please check if they are missing something?
Is conda still the recommended approach for cuda 12? thanks,

**Comment by chuanli11** [comment]
> @chuanli11 the setup instructions did not work on A100 or A10 instances. Could you please check if they are missing something? Is conda still the recommended approach for cuda 12? thanks,

Can you trying using conda 4.12.0. That is what i am using.

**Comment by chuanli11** [comment]
@eolecvk Actually i think you might be using a machine that has CUDA 11.8 instead of 12 (That is what Lambda A10 instances have). The way to check CUDA version is `nvcc --version`

This works for a fresh A10 instance:

```
sudo apt-get install python3-pybind11
virtualenv -p /usr/bin/python3.8 .venv-insightface
. .venv-insightface/bin/activate
pip install --upgrade pip
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
pip install -U openmim
mim install mmcv-full==1.5.0
git clone https://github.com/LambdaLabsML/insightface.git
cd insightface/detection/scrfd
pip install -r requirements/build.txt
pip install -v -e .
pip install -r requirements_add.tx
```

**Comment by chuanli11** [comment]
> `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html` freezes

It is unlikely a freeze. It just take very long time (5-10 mins) to finish in my case. @eolecvk

**Pull request merged**
